
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/tmp/cmake-3.28.1-linux-aarch64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.18.12-2-rpi-16k - aarch64
...
