name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Package
        run: |
          tar -cf lo3-linux.tar -C bin lo3
          zip lo3-linux.zip bin/lo3
          xz -zk lo3-linux.tar

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lo3-linux.zip
            lo3-linux.tar
            lo3-linux.tar.xz

  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -B build
          cmake --build build

      - name: Package
        run: |
          Compress-Archive -Path bin\lo3.exe -DestinationPath lo3-windows.zip
          tar -cf lo3-windows.tar -C bin lo3.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            lo3-windows.zip
            lo3-windows.tar
